/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskRouteImport } from './routes/ask'
import { Route as FactsRouteImport } from './routes/facts'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as LoopsRouteImport } from './routes/loops'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as EntitiesIndexRouteImport } from './routes/entities.index'
import { Route as EntitiesIdRouteImport } from './routes/entities.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const FactsRoute = FactsRouteImport.update({
  id: '/facts',
  path: '/facts',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LoopsRoute = LoopsRouteImport.update({
  id: '/loops',
  path: '/loops',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesIndexRoute = EntitiesIndexRouteImport.update({
  id: '/entities/',
  path: '/entities/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesIdRoute = EntitiesIdRouteImport.update({
  id: '/entities/$id',
  path: '/entities/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/facts': typeof FactsRoute
  '/graph': typeof GraphRoute
  '/insights': typeof InsightsRoute
  '/loops': typeof LoopsRoute
  '/reminders': typeof RemindersRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/entities/$id': typeof EntitiesIdRoute
  '/entities/': typeof EntitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/facts': typeof FactsRoute
  '/graph': typeof GraphRoute
  '/insights': typeof InsightsRoute
  '/loops': typeof LoopsRoute
  '/reminders': typeof RemindersRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/entities/$id': typeof EntitiesIdRoute
  '/entities': typeof EntitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/facts': typeof FactsRoute
  '/graph': typeof GraphRoute
  '/insights': typeof InsightsRoute
  '/loops': typeof LoopsRoute
  '/reminders': typeof RemindersRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/entities/$id': typeof EntitiesIdRoute
  '/entities/': typeof EntitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/facts'
    | '/graph'
    | '/insights'
    | '/loops'
    | '/reminders'
    | '/rules'
    | '/settings'
    | '/timeline'
    | '/entities/$id'
    | '/entities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/facts'
    | '/graph'
    | '/insights'
    | '/loops'
    | '/reminders'
    | '/rules'
    | '/settings'
    | '/timeline'
    | '/entities/$id'
    | '/entities'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/facts'
    | '/graph'
    | '/insights'
    | '/loops'
    | '/reminders'
    | '/rules'
    | '/settings'
    | '/timeline'
    | '/entities/$id'
    | '/entities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  FactsRoute: typeof FactsRoute
  GraphRoute: typeof GraphRoute
  InsightsRoute: typeof InsightsRoute
  LoopsRoute: typeof LoopsRoute
  RemindersRoute: typeof RemindersRoute
  RulesRoute: typeof RulesRoute
  SettingsRoute: typeof SettingsRoute
  TimelineRoute: typeof TimelineRoute
  EntitiesIdRoute: typeof EntitiesIdRoute
  EntitiesIndexRoute: typeof EntitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facts': {
      id: '/facts'
      path: '/facts'
      fullPath: '/facts'
      preLoaderRoute: typeof FactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loops': {
      id: '/loops'
      path: '/loops'
      fullPath: '/loops'
      preLoaderRoute: typeof LoopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/': {
      id: '/entities/'
      path: '/entities'
      fullPath: '/entities/'
      preLoaderRoute: typeof EntitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$id': {
      id: '/entities/$id'
      path: '/entities/$id'
      fullPath: '/entities/$id'
      preLoaderRoute: typeof EntitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  FactsRoute: FactsRoute,
  GraphRoute: GraphRoute,
  InsightsRoute: InsightsRoute,
  LoopsRoute: LoopsRoute,
  RemindersRoute: RemindersRoute,
  RulesRoute: RulesRoute,
  SettingsRoute: SettingsRoute,
  TimelineRoute: TimelineRoute,
  EntitiesIdRoute: EntitiesIdRoute,
  EntitiesIndexRoute: EntitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
